jdbc.datasource-proxy.json-format=true
jdbc.datasource-proxy.logging=slf4j
jdbc.datasource-proxy.query.enable-logging=true
logbook.minimum-status=500
logbook.strategy=body-only-if-status-at-least
logging.level.net.ttddyy.dsproxy.listener.logging.SLF4JQueryLoggingListener=debug
logging.level.org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor=warn
#logging.level.org.springframework.jdbc.support.JdbcTransactionManager=debug
#logging.level.org.springframework.security=debug
logging.level.org.springframework.security.web.csrf.CsrfFilter=debug
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=debug
# TODO [Advisor]: Liveness and readiness probes are now enabled by default in Spring Boot 4.0. If you do not need those probes, keep this property. Otherwise, delete this property to adopt the new defaults. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-4.0-Migration-Guide#liveness-and-readiness-probes
management.endpoint.health.probes.enabled=false
mybatis.configuration.default-fetch-size=100
mybatis.configuration.lazy-loading-enabled=true
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=org.terasoluna.tourreservation.domain.model,org.terasoluna.tourreservation.domain.repository
spring.application.name=tourreservation
spring.jackson.use-jackson2-defaults=true
spring.web.resources.cache.period=1d
